accounts/urls.py
from django.conf.urls import url

from . import views
from django.contrib.auth.decorators import login_required

app_name = 'accounts'

urlpatterns = [
    url(r'^register/$', views.UserCreateFormView.as_view(), name='register'),
    url(r'^login/$', views.UserLoginFormView.as_view(), name='login'),
    url(r'^$', views.FindRoomView.as_view(), name='index'),
    url(r'^profile/$', views.users_list_view, name='profile'),
    url(r'^profile/reservation/(?P<pk>[0-9]+)$', views.reservation_detail_view, name='reservation-detail'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^contact/$', views.contact_view, name='contact'),
    url(r'^mail/$', views.send_mail_view, name='mail'),
    url(r'^gallery/$', views.gallery_view, name='gallery'),
    url(r'^room_list/$', views.room_view, name='room-list'),
    url(r'^room_detail/(?P<pk>[0-9]+)/$', login_required(views.RoomDetailView.as_view()), name='room-detail'),
    url(r'^room_detail/(?P<pk>[0-9]+)/reserve/$', login_required(views.RoomReserveView.as_view()), name='reserve-room'),
]

hotel/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/accounts/')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
]

accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save, post_delete, pre_delete
from django.dispatch import receiver
from django.db.models import Q
import datetime


TYPE_CHOICES = (
    ('1', '1-osobowy'),
    ('2', '2-osobowy'),
    ('3', '3-osobowy'),
    ('4', '4-osobowy')
)

PAYMENT_CHOICES = (
    (1, u'Gotówka'),
    (2, u'Karta'),
    (3, u'Przelew'),
)


class Profile(models.Model):
    ROLE_CHOICES = (
        ('Klient', 'Klient'),
        ('Pracownik', 'Pracownik'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name=(u'Użytkownik'))
    hire_date = models.DateField(null=True, blank=True, verbose_name=('Data zatrudnienia'))
    role = models.CharField(max_length=9, choices=ROLE_CHOICES, null=True, blank=True, verbose_name=(u"Kto"), default='Klient')

    @receiver(post_save, sender = User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

    def __str__(self):
        return str(self.user.username)

    def is_employee(self):
        if self.role == 'Pracownik':
            return True
        else:
            return False

    class Meta:
        verbose_name = u'Profil'
        verbose_name_plural = u'Profile'


class Room(models.Model):
    type = models.CharField(max_length=9, choices=TYPE_CHOICES, default=None, verbose_name=(u'Rodzaj'))
    price = models.FloatField(default=None, verbose_name=('Cena/noc'))
    is_occupied = models.BooleanField(default=False, verbose_name=(u'Czy zajety'))

    class Meta:
        verbose_name = u'Pokój'
        verbose_name_plural = u'Pokoje'

    def __str__(self):
        return str(self.pk)

    def set_room_occupied(self):
        self.is_occupied = True

    def set_room_free(self):
        self.is_occupied = False


class Vacation(models.Model):
    employee = models.ForeignKey(User, on_delete=models.CASCADE, default=None, verbose_name=('Pracownik'))
    start_date = models.DateField(default=None, verbose_name=(u'Data rozpoczęcia'))
    end_date = models.DateField(default=None, verbose_name=('Data zakończenia'))

    class Meta:
        verbose_name = u'Urlop'
        verbose_name_plural = u'Urlopy'


class Reservation(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE, default=None, verbose_name=u"Nr pokoju")
    client = models.ForeignKey(User, on_delete=models.CASCADE, default=None, verbose_name=u"Nazwa użytkownika")
    start_date = models.DateField(default=None, verbose_name=u"Data rozpoczęcia")
    end_date = models.DateField(default=None, verbose_name=u"Data zakończenia")
    is_confirmed = models.BooleanField(default=False, verbose_name=u'Czy potwierdzona')

    class Meta:
        verbose_name = u'Rezerwacja'
        verbose_name_plural = u'Rezerwacje'

    def __str__(self):
        return str(self.pk)

    def add_reservation(self, end_date, start_date, client, room):
        self.end_date = end_date
        self.start_date = start_date
        self.client = client
        self.room = room
        self.room.set_room_occupied()
        self.room.save()
        self.save()
        return self

    def get_reservations(self):
        return Reservation.objects.all()

    def confirm_reservation(self):
        self.is_confirmed = True


@receiver(post_delete, sender=Reservation)
def _reservation_delete(sender, instance, **kwargs):
    q = instance.room.pk
    if not Reservation.objects.filter(Q(room_id=q)).exists():
        r = Room.objects.get(id=q)
        r.set_room_free()
        r.save()


class Payment(models.Model):
    reservation = models.OneToOneField(Reservation, default=None, on_delete=models.CASCADE, verbose_name=(u'Nr rezerwacji'))
    price = models.FloatField(default=None, verbose_name=('Koszt'))
    discount = models.FloatField(default=0.0, verbose_name=(u'Zniżka'))
    is_paid = models.BooleanField(default=False, verbose_name=u"Czy opłacone")
    method = models.SmallIntegerField(default=0, choices=PAYMENT_CHOICES, verbose_name=u'Sposób płatności')

    class Meta:
        verbose_name = u'Płatność'
        verbose_name_plural = u'Płatności'

    def __str__(self):
        return str(self.pk)

    def add_payment(self, reservation, method):
        self.reservation = reservation
        self.price = self.calculate_price()
        self.method = method
        self.save()
        return self

    def calculate_price(self):
        days = (self.reservation.end_date - self.reservation.start_date).days
        price = float(days) * float(self.reservation.room.price)
        print(price)
        return price

    def confirm_payment(self):
        self.is_paid = True
        self.save()


class Salary(models.Model):
    employee = models.ForeignKey(User, on_delete=models.CASCADE, default=None, verbose_name=('Pracownik'))
    size = models.FloatField(default=1200.0, verbose_name=u"Ile")
    bonus = models.FloatField(default=0, verbose_name=u'Premia')
    month = models.DateField(default=None, verbose_name=u'Miesiąc')

    def __str__(self):
        return str(self.pk)

    class Meta:
        verbose_name = u'Wypłata'
        verbose_name_plural = u'Wypłaty'

    def calculate_bonus(self):
        pass

accounts/forms.py
# -*- coding: utf-8 -*-
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django import forms
from django.contrib.auth.models import User
from models import Profile, Room, Reservation, TYPE_CHOICES, PAYMENT_CHOICES
from django.contrib.admin.widgets import AdminDateWidget
import datetime
from datetimewidget.widgets import DateTimeWidget, DateWidget, TimeWidget


class UserCreateForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'email', 'first_name', 'last_name']
        help_texts = {
            'username': None,
            'password1': None,
            'password2': None,
            'email': None,
            'first_name': None,
            'last_name': None
        }
        labels = {
            'username': u'Nazwa użytkownika',
            'password1': u'Hasło',
            'password2': u'Powtórz hasło',
            'email': u'Adres e-mail',
            'first_name': u'Imię',
            'last_name': u'Nazwisko'
        }


class UserLoginForm(AuthenticationForm):
    pass


class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['hire_date']


class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True)
    from_email.label = "Od:"
    subject = forms.CharField(required=True)
    subject.label = "Temat"
    message = forms.CharField(widget=forms.Textarea, required=True)
    message.label = u"Wiadomość"


class FindRoomForm(forms.Form):
    start_date = forms.DateField(widget=DateWidget(usel10n=True, bootstrap_version=3))
    end_date = forms.DateField(widget=DateWidget(usel10n=True, bootstrap_version=3))
    type = forms.CharField(max_length=9, widget=forms.Select(choices=TYPE_CHOICES), )
    start_date.label = u"Od"
    end_date.label = u"Do"
    type.label = u"Rodzaj pokoju"


class AddRoomForm(forms.Form):
    type = forms.CharField(max_length=9, widget=forms.Select(choices=TYPE_CHOICES), )
    type.label = u"Rodzaj pokoju"
    price = forms.IntegerField(max_value=5000)
    price.label = u"Cena/noc"


class ReserveRoomForm(forms.Form):
    start_date = forms.DateField(widget=DateWidget(usel10n=True, bootstrap_version=3))
    end_date = forms.DateField(widget=DateWidget(usel10n=True, bootstrap_version=3))
    payment_method = forms.CharField(max_length=20, widget=forms.Select(choices=PAYMENT_CHOICES))
    payment_method.label = u"Sposób płatności"
    start_date.label = u"Od"
    end_date.label = u"Do"

accounts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import View, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import login
from django.contrib.auth.models import User
from accounts.forms import UserCreateForm, UserLoginForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.urls import reverse, reverse_lazy
from django.db import transaction
from forms import  ContactForm, UserForm, FindRoomForm, ReserveRoomForm
from django.contrib import messages
from models import Room, Reservation, Payment
from django.core.mail import send_mail, BadHeaderError
from django.db.models import Q


@login_required
def logout_view(request):
    logout(request)
    return redirect('accounts:index')


def reservation_detail_view(request, pk):
    reservation = Reservation.objects.get(id=pk)
    return render(request, 'accounts/reservation_detail.html', {'reservation': reservation})


@login_required
def my_view2(request):
    reservations = Reservation.objects.filter(client=request.user.pk)
    return render(request, 'accounts/profile.html', {'reservations': reservations})


class FindRoomView(View):
    form = FindRoomForm
    template_name = 'accounts/index.html'

    def get(self, request):
        if request.user.is_authenticated():
            form = self.form
            return render(request, self.template_name, {'form': form})
        else:
            return redirect('accounts:login')

    def post(self, request):
        form = FindRoomForm(request.POST)
        if form.is_valid():
            from_date = form.cleaned_data['start_date']
            to_date = form.cleaned_data['end_date']
            dates = [from_date, to_date]

            room_type = form.cleaned_data['type']
            rooms_with_no_reservation = Room.objects.filter(Q(reservation__pk__isnull=True))
            rooms_with_valid_free_date = Room.objects.exclude((  (Q(reservation__end_date__gte=from_date) & Q(reservation__end_date__lte=to_date))
                                          | (Q(reservation__start_date__gte=from_date) & Q(reservation__start_date__lte=to_date))
                                          | (Q(reservation__start_date__lte=from_date) & Q(reservation__end_date__gte=to_date))))
            query_result = (rooms_with_no_reservation | rooms_with_valid_free_date).filter(Q(type=room_type)).distinct()

            return render(request, 'accounts/room_list.html', {'rooms': query_result})
        else:
            return render(request, self.template_name, {'form': form})


class RoomReserveView(View):
    form = ReserveRoomForm
    template_name = 'accounts/room_reserve.html'
    room_id = Room.objects.all()
    success_template = 'accounts/room_reserve_success.html'

    def get(self, request, pk):
        form = self.form
        room = Room.objects.get(id=pk)
        return render(request, self.template_name, {'form': form,
                                                    'room': room})

    def post(self, request, pk):
        form = ReserveRoomForm(request.POST)
        if form.is_valid():
            from_date = form.cleaned_data['start_date']
            to_date = form.cleaned_data['end_date']
            payment_method = form.cleaned_data['payment_method']
            room_id = Room.objects.get(id=pk)
            rooms_with_valid_free_date = Room.objects.filter(
                ((Q(reservation__end_date__gte=from_date) & Q(reservation__end_date__lte=to_date))
                 | (Q(reservation__start_date__gte=from_date) & Q(reservation__start_date__lte=to_date))
                 | (Q(reservation__start_date__lte=from_date) & Q(reservation__end_date__gte=to_date)))).distinct()
            if rooms_with_valid_free_date.filter(pk=room_id.pk).exists():
                return render(request, self.template_name, {'form': form})
            else:
                q = Reservation.add_reservation(Reservation(), end_date=to_date, start_date=from_date,
                                                client=request.user, room=room_id)
                p = Payment.add_payment(Payment(), q, payment_method)
                return render(request, self.success_template, {'reservation': q,
                                                               'payment': p})
        else:
            return render(request, self.template_name, {'form': form})


class UserCreateFormView(View):
    user_form = UserCreateForm
    template_name = 'accounts/register_form.html'

    def get(self, request):
        if request.user.is_authenticated():
            return redirect('accounts:index')
        else:
            user_form = self.user_form
            return render(request, self.template_name, {'user_form': user_form})

    def post(self, request):
        user_form = UserCreateForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            if user is not None:
                login(request, user)
                return redirect('accounts:index')
        else:
            return render(request, self.template_name, {'user_form': user_form})


class UserLoginFormView(View):
    form = UserLoginForm
    template_name = 'accounts/login_form.html'

    def get(self, request):
        if request.user.is_authenticated():
            return redirect('accounts:index')
        else:
            form = self.form
            return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            if user is not None:
                login(request, user)
                return redirect('accounts:index')
        else:
            return render(request, self.template_name, {'form': form})


def send_mail_view(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            try:
                send_mail(subject, message, from_email, ['mail@hotel.pod.pies'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('accounts:index')
    return render(request, "accounts/send_mail.html", {'form': form})


def gallery_view(request):
    return render(request, 'accounts/gallery.html')


@login_required
def room_view(request):
    rooms = Room.objects.all()
    return render(request, 'accounts/room_list.html', {'rooms': rooms})


class RoomDetailView(DetailView):
    model = Room
    template_name = 'accounts/room_detail.html'


class ReservationDetailView(DetailView):
    model = Room
    template_name = 'accounts/reservation_detail.html'


@login_required
def users_list_view(request):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            return redirect('/admin')
        else:
            return my_view2(request)


def contact_view(request):
    return render(request, 'accounts/contact.html')

accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hotel</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}" />
             <script type="text/javascript"
     src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.8.3/jquery.min.js">
    </script>
        <script type="text/javascript"
     src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js">
    </script>
        {{ form.media }}
</head>
<body>
    <div>

        <nav class="navbar navbar-inverse" >
        <div class="containter-fluid">

            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'accounts:index' %}">
                    HOME
                </a>
            </div>
            <div class="navbar-collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'accounts:gallery' %}"> Galeria </a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:contact' %}"> Kontakt </a>
                    </li>

                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'accounts:profile' %}"> {{ user.username }} </a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:logout' %}"> Wyloguj&nbsp;&nbsp; &nbsp;&nbsp; </a>
                    </li>
                     <li>
                    {% else %}
                    <li>
                        <a href="{% url 'accounts:login' %}"> Zaloguj </a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:register' %}"> Zarejestruj&nbsp;&nbsp; &nbsp;&nbsp; </a>
                    </li>
                    <li>
                    {% endif %}
                </ul>
            </div>
        </div>
        </nav>
    </div>
   <div class="container">
        <div class="panel panel-default panel-findroom">
            <div class="panel-body">

                {% block content %}
                {% endblock %}

            </div>
        </div>
      </div>
    <footer class="footer">
          <div class="container">
            <p class="text-muted">Stopka</p>
          </div>
    </footer>
</body>
</html>

accounts/templates/accounts/contact.html
{% extends 'accounts/base.html' %}
{% load staticfiles %}

{% block content %}

    <h1>
        Kontakt
    </h1>
    <div>
        <ul class="list-unstyled">
            <li>
                <h3>Hotel Pod Psem</h3>
            </li>
            <li>
                Adres:
                <ul>
                    <li>
                        ul. Behawioralna 66
                    </li>
                    <li>
                        66-666 Szaolin
                    </li>
                </ul>
            </li>
            <li>
                Nr kontaktowy:
                <ul>
                    <li>
                        666 666 666
                    </li>
                    <li>
                        999 666 999
                    </li>
                </ul>
            </li>
            <li>
                Adres e-mail:
                <ul>
                    <li>
                        mail@hotel.pod.pies
                    </li>
                </ul>
            </li>
        </ul>
        <a href="{% url 'accounts:mail' %}">
            <button>Wyslij e-mail</button>
        </a>
    </div>

{% endblock %}

accounts/templates/accounts/gallery.html
{% extends 'accounts/base.html' %}

{% block content %}
      TU BEDZIE GALERIA!
{% endblock %}

accounts/templates/accounts/index.html
{% extends 'accounts/base.html' %}
{% load staticfiles %}

{% block content %}

                <h1>
                    Znajdź pokój
                </h1>
               <form action="" method="post">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    {{ form.as_p }}
                    <button type="submit">Szukaj</button>
                   <button type="reset" >Wyczyść</button>
               </form>
                <a href="{% url 'accounts:room-list' %}">
                    <button>Lista wszystkich pokoi</button>
                </a>



{% endblock %}

accounts/templates/accounts/layout.html
<html>
	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'accounts/layout.css' %}">
		<title>Serwis komputerowy</title>
		<meta name="description" content="Strona główna">
	</head>

	{%block content %}
	{% endblock %}

</html>

accounts/templates/accounts/login_form.html
{% extends 'accounts/base.html' %}
{% load staticfiles %}



{% block content %}

<h1>
    Logowanie
</h1>

<form class="in-form" action="" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="fieldWrapper">
                {{ field.errors }}
                {{ field.label_tag }}<br>
                {{ field }}
                {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
            </div>
        <br>
        {% endfor %}
            <div class="form-actions">
                <br><button type="submit">Zaloguj</button>
                <a href="{% url 'accounts:register' %}" style="text-decoration:none;">
                    <font size="2">
                        Nie masz konta? Zarejestruj!
                    </font>
                </a>
            </div>

</form>


{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'accounts/base.html' %}
{% load staticfiles %}

{% block content %}
<h1>
    {% if user.profile.is_employee %}
        Pracownik {{ user }}
    {% else %}
        Klient {{ user }}
    {% endif %}
</h1>

    <ul class="list-unstyled">
        <li>
            Imię: {{ user.first_name }}
        </li>
        <li>
            Nazwisko: {{ user.last_name }}
        </li>
        <li>
            E-mail: {{ user.email }}
        </li>
        {% if not user.profile.is_employee %}
            <li>
            Rezerwacje: <br>
                <div class="list-group">
                    {% for reservation in reservations %}
                         <a href="{% url 'accounts:reservation-detail' reservation.id %}" class="list-group-item">
                             Pokój nr {{ reservation.room }} <br>
                             {{ reservation.room.get_type_display }}
                             {% if reservation.room.is_occupied %}
                                Zajęty w dniach:
                             <ul>
                                 {% for date in reservation.room.reservation_set.all %}
                                 <li>
                                     {{ date.start_date }} - {{ date.end_date }}
                                 </li>
                                 {% endfor %}
                             </ul>
                             {% endif %}
                         </a>
                    {% endfor %}
                     </div>
            </li>
        {% else %}
        <li>
            Data zatrudnienia: {{ user.profile.hire_date }}
        </li>
        {% endif %}
    </ul>
{% endblock %}

accounts/templates/accounts/reservation_detail.html
{% extends 'accounts/base.html' %}
{% load staticfiles %}

{% block content %}
                     <h1>
                  Szczegóły rezerwacji {{ reservation }}
                </h1>
                <ul>
                    <li>
                        Numer pokoju: {{ reservation.room.id }}
                    </li>
                    <li>
                        Czas rezerwacji: {{ reservation.start_date }} - {{ reservation.end_date }}
                    </li>
                    <li>
                        Koszt: {{ reservation.payment.price }} zł
                    </li>
                    <li>
                        Sposób płatności: {{ reservation.payment.get_method_display }}
                    </li>
                    <li>
                        Czy potwierdzono:
                        {% if reservation.is_confirmed %}
                           <font color="green">POTWIERDZONO</font>
                        {% else %}
                           <font color="blue">NIE POTWIERDZONO</font>
                        {% endif %}
                    </li>
                    <li>
                         Czy zapłacono:
                        {% if reservation.payment.is_paid %}
                           <font color="green">ZAPŁACONO</font>
                        {% else %}
                           <font color="blue">NIE ZAPŁACONO</font>
                        {% endif %}
                    </li>

                </ul>
                <a href="{% url 'accounts:profile' %}">
                        <button>Wróć do profilu</button>
            </a>



{% endblock %}

accounts/templates/accounts/room_detail.html
{% extends 'accounts/base.html' %}
{% load staticfiles %}

{% block content %}
                    Szczegóły pokoju nr {{ room.id }}
                    <ul>
                        <li>
                             {{ room.get_type_display }}
                        </li>
                        <li>
                             {{ room.price }} zł/doba
                        </li>
                         <li>
                             {% if room.is_occupied %}
                             Zajęty w dniach:
                             <ul>
                                  {% for data in room.reservation_set.all %}
                                    <li>
                                        {{ data.start_date }} - {{ data.end_date }}
                                    </li>
                                 {% endfor %}
                             </ul>

                             {% else %}
                             Wolny
                             {% endif %}
                        </li>
                    </ul>
                    <a href="{% url 'accounts:reserve-room' room.pk %}">
                        <button>Rezerwuj</button>
                    </a>
                    <a href="{% url 'accounts:room-list' %}">
                        <button>Wróć do listy</button>
                    </a>
                    <a href="{% url 'accounts:index' %}">
                        <button>Wróć do wyszukiwania</button>
                    </a>



{% endblock %}

accounts/templates/accounts/room_list.html
{% extends 'accounts/base.html' %}
{% load staticfiles %}

{% block content %}
                    {% if not rooms %}
                        <br>Brak pokoi do wyświetlenia
                    {% endif %}
                    {% for room in rooms %}
                     <div class="list-group">
                         <a href="{% url 'accounts:room-detail' room.id %}" class="list-group-item">
                             Pokój nr {{ room }} <br>
                             {{ room.get_type_display }}
                             {% if room.is_occupied %}
                                Zajęty w dniach:
                             <ul>
                                 {% for date in room.reservation_set.all %}
                                 <li>
                                     {{ date.start_date }} - {{ date.end_date }}
                                 </li>
                                 {% endfor %}
                             </ul>

                             {% else %}
                                 Wolny
                             {% endif %}
                         </a>
                     </div>
                    {% endfor %}
                    <a href="{% url 'accounts:index' %}">
                        <button>Wróć do wyszukiwania</button>
                    </a>

{% endblock %}

accounts/templates/accounts/room_reserve.html
{% extends 'accounts/base.html' %}
{% load staticfiles %}

{% block content %}

                <h1>
                    Rezerwuj pokój nr {{ room }}
                </h1>
              <form action="." method="post">
               {% csrf_token %}
        {% for field in form %}
            <div class="fieldWrapper">
                {{ field.errors }}
                {{ field.label_tag }}<br>
                {{ field }}
                {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
            </div><br>
        {% endfor %}
                  <ul>
                        <li>
                             {{ room.get_type_display }}
                        </li>
                        <li>
                             {{ room.price }} zł/doba
                        </li>
                         <li>
                             {% if room.is_occupied %}
                             Zajęty w dniach:
                             <ul>
                                  {% for data in room.reservation_set.all %}
                                    <li>
                                        {{ data.start_date }} - {{ data.end_date }}
                                    </li>
                                 {% endfor %}
                             </ul>

                             {% else %}
                             Wolny
                             {% endif %}
                        </li>
                    </ul>
                <button type="submit" >Zarezerwuj</button>
                <button type="reset" >Wyczyść</button>
              </form>
            <a href="{% url 'accounts:room-list' %}">
                        <button>Wróć do listy</button>
            </a>


{% endblock %}

accounts/templates/accounts/room_reserve_success.html
{% extends 'accounts/base.html' %}
{% load staticfiles %}

{% block content %}

                <h1>
                   Zarezerwowano pokój {{ reservation.room }}
                   <h3>Prosimy o potwierdzenie rezerwacji<h3>
                </h1>
                <ul>
                    <li>
                        Czas rezerwacji: {{ reservation.start_date }} - {{ reservation.end_date }}
                    </li>
                    <li>
                        Koszt: {{ payment.price }}
                    </li>
                    <li>
                        Sposób płatności: {{ payment.get_method_display }}
                    </li>

                </ul>
                <a href="{% url 'accounts:index' %}">
                        <button>Wróć do wyszkuiwania</button>
            </a>

{% endblock %}